<?php
/**
 * System generated by SysGen (System Generator with Formdin Framework) 
 * Download SysGen: https://github.com/bjverde/sysgen
 * Download Formdin Framework: https://github.com/bjverde/formDin
 * 
 * SysGen  Version: 1.11.0
 * FormDin Version: 4.11.0
 * 
 * System concursomembroadm created in: 2021-03-10 20:42:27
 */
class SociosDAO  extends Dao
{
    private static $sqlBasicSelect = 'SELECT cnpj_basico
                                            ,identificador_socio
                                            ,nome_socio_razao_social
                                            ,cpf_cnpj_socio
                                            ,qualificacao_socio
                                            ,data_entrada_sociedade
                                            ,pais
                                            ,representante_legal
                                            ,nome_do_representante
                                            ,qualificacao_representante_legal
                                            ,faixa_etaria
                                        FROM socios';

    public function __construct($tpdo=null)
    {
        parent::__construct($tpdo);
        $this->setTabelaName('socios');
    }
    //--------------------------------------------------------------------------------
    public function selectCount()
    {
        $sql = 'select count(cnpj_basico) as qtd from '.$this->getTabelaName();
        $result = $this->getTPDOConnection()->executeSql($sql);
        $result = ArrayHelper::getArray($result,0);
        $result = ArrayHelper::get($result,'qtd');
        return $result;
    }    
    //--------------------------------------------------------------------------------
    public function insert( array $linhaArquivoCsv )
    {
        $values = array(  $linhaArquivoCsv[0]
                        , $linhaArquivoCsv[1]
                        , $linhaArquivoCsv[2]
                        , $linhaArquivoCsv[3]
                        , $linhaArquivoCsv[4]
                        , $linhaArquivoCsv[5]
                        , $linhaArquivoCsv[6]
                        , $linhaArquivoCsv[7]
                        , $linhaArquivoCsv[8]
                        , $linhaArquivoCsv[9]
                        , $linhaArquivoCsv[10]
                        );
        $sql = 'INSERT INTO estabelecimento
        (cnpj_basico        
        ,identificador_socio
        ,nome_socio_razao_social
        ,cpf_cnpj_socio
        ,qualificacao_socio
        ,data_entrada_sociedade
        ,pais
        ,representante_legal
        ,nome_do_representante
        ,qualificacao_representante_legal
        ,faixa_etaria
        )
        VALUES
        (?
        ,?
        ,?
        ,?
        ,?
        ,?
        ,?
        ,?
        ,?
        ,?
        ,?)';
        $result = $this->executeSql($sql, $values);
        return true;
    }
}
?>