<?php
/**
 * System generated by SysGen (System Generator with Formdin Framework) 
 * Download SysGenAd: https://github.com/bjverde/sysgenad
 * Download Formdin5 Framework: https://github.com/bjverde/formDin5
 * 
 * SysGen  Version: 0.6.0
 * FormDin Version: 5.0.0
 * 
 * System cnpjrfb2 created in: 2021-11-20 00:51:44
 */
class empresa extends TRecord
{
    const TABLENAME = 'empresa';
    const PRIMARYKEY= 'CNPJ_BASICO';
    const IDPOLICY  = 'serial'; //{max, serial}

    public function __construct($id = NULL, $callObjectLoad = TRUE)
    {
        parent::__construct($id, $callObjectLoad);
        parent::addAttribute('RAZAO_SOCIAL');
        parent::addAttribute('NATUREZA_JURIDICA');
        parent::addAttribute('QUALIFICACAO_RESPONSAVEL');
        parent::addAttribute('CAPITAL_SOCIAL');
        parent::addAttribute('PORTE_EMPRESA');
        parent::addAttribute('ENTE_FEDERATIVO_RESPONSAVEL');
    }

}
?>