<?php
/**
 * System generated by SysGen (System Generator with Formdin Framework) 
 * Download SysGenAd: https://github.com/bjverde/sysgenad
 * Download Formdin5 Framework: https://github.com/bjverde/formDin5
 * 
 * SysGen  Version: 0.6.0
 * FormDin Version: 5.0.0
 * 
 * System cnpjrfb created in: 2021-11-19 22:41:13
 */
class estabelecimento extends TRecord
{
    const TABLENAME = 'estabelecimento';
    const PRIMARYKEY= 'CNPJ_BASICO';
    const IDPOLICY  = 'serial'; //{max, serial}

    public function __construct($id = NULL, $callObjectLoad = TRUE)
    {
        parent::__construct($id, $callObjectLoad);
        parent::addAttribute('CNPJ_ORDEM');
        parent::addAttribute('CNPJ_DV');
        parent::addAttribute('IDENTIFICADOR_MATRIZ_FILIAL');
        parent::addAttribute('NOME_FANTASIA');
        parent::addAttribute('SITUACAO_CADASTRAL');
        parent::addAttribute('DATA_SITUACAO_CADASTRAL');
        parent::addAttribute('MOTIVO_SITUACAO_CADASTRAL');
        parent::addAttribute('NOME_CIDADE_EXTERIOR');
        parent::addAttribute('PAIS');
        parent::addAttribute('DATA_INICIO_ATIVIDADE');
        parent::addAttribute('CNAE_FISCAL_PRINCIPAL');
        parent::addAttribute('CNAE_FISCAL_SECUNDARIA');
        parent::addAttribute('TIPO_LOGRADOURO');
        parent::addAttribute('LOGRADOURO');
        parent::addAttribute('NUMERO');
        parent::addAttribute('COMPLEMENTO');
        parent::addAttribute('BAIRRO');
        parent::addAttribute('CEP');
        parent::addAttribute('UF');
        parent::addAttribute('MUNICIPIO');
        parent::addAttribute('DDD_1');
        parent::addAttribute('TELEFONE_1');
        parent::addAttribute('DDD_2');
        parent::addAttribute('TELEFONE_2');
        parent::addAttribute('DDD_FAX');
        parent::addAttribute('FAX');
        parent::addAttribute('CORREIO_ELETRONICO');
        parent::addAttribute('SITUACAO_ESPECIAL');
        parent::addAttribute('DATA_SITUACAO_ESPECIAL');
    }

}
?>