<?php
/**
 * System generated by SysGen (System Generator with Formdin Framework) 
 * Download SysGenAd: https://github.com/bjverde/sysgenad
 * Download Formdin5 Framework: https://github.com/bjverde/formDin5
 * 
 * SysGen  Version: 0.6.0
 * FormDin Version: 5.0.0
 * 
 * System cnpjrfb created in: 2021-11-19 22:41:13
 */
class estabelecimento extends TRecord
{
    const TABLENAME = 'estabelecimento';
    const PRIMARYKEY= 'cnpj_basico';
    const IDPOLICY  = 'serial'; //{max, serial}

    public function __construct($id = NULL, $callObjectLoad = TRUE)
    {
        parent::__construct($id, $callObjectLoad);
        parent::addAttribute('cnpj_ordem');
        parent::addAttribute('cnpj_dv');
        parent::addAttribute('identificador_matriz_filial');
        parent::addAttribute('nome_fantasia');
        parent::addAttribute('situacao_cadastral');
        parent::addAttribute('data_situacao_cadastral');
        parent::addAttribute('motivo_situacao_cadastral');
        parent::addAttribute('nome_cidade_exterior');
        parent::addAttribute('pais');
        parent::addAttribute('data_inicio_atividade');
        parent::addAttribute('cnae_fiscal_principal');
        parent::addAttribute('cnae_fiscal_secundaria');
        parent::addAttribute('tipo_logradouro');
        parent::addAttribute('logradouro');
        parent::addAttribute('numero');
        parent::addAttribute('complemento');
        parent::addAttribute('bairro');
        parent::addAttribute('cep');
        parent::addAttribute('uf');
        parent::addAttribute('municipio');
        parent::addAttribute('ddd_1');
        parent::addAttribute('telefone_1');
        parent::addAttribute('ddd_2');
        parent::addAttribute('telefone_2');
        parent::addAttribute('ddd_fax');
        parent::addAttribute('fax');
        parent::addAttribute('correio_eletronico');
        parent::addAttribute('situacao_especial');
        parent::addAttribute('data_situacao_especial');
    }

}
?>