<?php
/**
 * System generated by SysGen (System Generator with Formdin Framework) 
 * Download SysGenAd: https://github.com/bjverde/sysgenad
 * Download Formdin5 Framework: https://github.com/bjverde/formDin5
 * 
 * SysGen  Version: 0.6.0
 * FormDin Version: 5.0.0
 * 
 * System cnpjrfb created in: 2021-11-19 22:41:14
 */
class socios extends TRecord
{
    const TABLENAME = 'socios';
    const PRIMARYKEY= 'CNPJ_BASICO';
    const IDPOLICY  = 'serial'; //{max, serial}

    public function __construct($id = NULL, $callObjectLoad = TRUE)
    {
        parent::__construct($id, $callObjectLoad);
        parent::addAttribute('IDENTIFICADOR_SOCIO');
        parent::addAttribute('NOME_SOCIO_RAZAO_SOCIAL');
        parent::addAttribute('CPF_CNPJ_SOCIO');
        parent::addAttribute('QUALIFICACAO_SOCIO');
        parent::addAttribute('DATA_ENTRADA_SOCIEDADE');
        parent::addAttribute('PAIS');
        parent::addAttribute('REPRESENTANTE_LEGAL');
        parent::addAttribute('NOME_DO_REPRESENTANTE');
        parent::addAttribute('QUALIFICACAO_REPRESENTANTE_LEGAL');
        parent::addAttribute('FAIXA_ETARIA');
    }

}
?>