<?php
/**
 * System generated by SysGen (System Generator with Formdin Framework) 
 * Download SysGenAd: https://github.com/bjverde/sysgenad
 * Download Formdin5 Framework: https://github.com/bjverde/formDin5
 * 
 * SysGen  Version: 0.6.0
 * FormDin Version: 5.0.0
 * 
 * System cnpjrfb created in: 2021-11-19 22:41:14
 */
class socios extends TRecord
{
    const TABLENAME = 'socios';
    const PRIMARYKEY= 'cnpj_basico';
    const IDPOLICY  = 'serial'; //{max, serial}

    public function __construct($id = NULL, $callObjectLoad = TRUE)
    {
        parent::__construct($id, $callObjectLoad);
        parent::addAttribute('identificador_socio');
        parent::addAttribute('nome_socio_razao_social');
        parent::addAttribute('cpf_cnpj_socio');
        parent::addAttribute('qualificacao_socio');
        parent::addAttribute('data_entrada_sociedade');
        parent::addAttribute('pais');
        parent::addAttribute('representante_legal');
        parent::addAttribute('nome_do_representante');
        parent::addAttribute('qualificacao_representante_legal');
        parent::addAttribute('faixa_etaria');
    }

}
?>