<?php
/**
 * System generated by SysGen (System Generator with Formdin Framework) 
 * Download SysGen: https://github.com/bjverde/sysgen
 * Download Formdin Framework: https://github.com/bjverde/formDin
 * 
 * SysGen  Version: 1.11.0
 * FormDin Version: 4.11.0
 * 
 * System concursomembroadm created in: 2021-03-10 20:42:27
 */
class EstabelecimentoDAO  extends Dao
{
    private static $sqlBasicSelect = 'SELECT cnpj_basico
                                            ,cnpj_ordem
                                            ,cnpj_dv
                                            ,identificador_matriz_filial
                                            ,nome_fantasia
                                            ,situacao_cadastral
                                            ,data_situacao_cadastral
                                            ,motivo_situacao_cadastral
                                            ,nome_cidade_exterior
                                            ,pais
                                            ,data_inicio_atividade
                                            ,cnae_fiscal_principal
                                            ,cnae_fiscal_secundaria
                                            ,tipo_logradouro
                                            ,logradouro
                                            ,numero
                                            ,complemento
                                            ,bairro
                                            ,cep
                                            ,uf
                                            ,municipio
                                            ,ddd_1
                                            ,telefone_1
                                            ,ddd_2
                                            ,telefone_2
                                            ,ddd_fax
                                            ,fax
                                            ,correio_eletronico
                                            ,situacao_especial
                                            ,data_situacao_especial
                                        FROM estabelecimento';

    public function __construct($tpdo=null)
    {
        parent::__construct($tpdo);
        $this->setTabelaName('estabelecimento');
    }
    //--------------------------------------------------------------------------------
    public function selectCount()
    {
        $sql = 'select count(cnpj_basico) as qtd from '.$this->getTabelaName();
        $result = $this->getTPDOConnection()->executeSql($sql);
        $result = ArrayHelper::getArray($result,0);
        $result = ArrayHelper::get($result,'qtd');
        return $result;
    }    
    //--------------------------------------------------------------------------------
    public function insert( array $linhaArquivoCsv )
    {
        $values = array( $linhaArquivoCsv[0]
                        , $linhaArquivoCsv[1]
                        , $linhaArquivoCsv[2]
                        , $linhaArquivoCsv[3]
                        , $linhaArquivoCsv[4]
                        , $linhaArquivoCsv[5]
                        , $linhaArquivoCsv[6]
                        , $linhaArquivoCsv[7]
                        , $linhaArquivoCsv[8]
                        , $linhaArquivoCsv[9]
                        , $linhaArquivoCsv[10]
                        , $linhaArquivoCsv[11]
                        , $linhaArquivoCsv[12]
                        , $linhaArquivoCsv[13]
                        , $linhaArquivoCsv[14]
                        , $linhaArquivoCsv[15]
                        , $linhaArquivoCsv[16]
                        , $linhaArquivoCsv[17]
                        , $linhaArquivoCsv[18]
                        , $linhaArquivoCsv[19]
                        , $linhaArquivoCsv[20]
                        , $linhaArquivoCsv[21]
                        , $linhaArquivoCsv[22]
                        , $linhaArquivoCsv[23]
                        , $linhaArquivoCsv[24]
                        , $linhaArquivoCsv[25]
                        , $linhaArquivoCsv[26]
                        , $linhaArquivoCsv[27]
                        , $linhaArquivoCsv[28]
                        , $linhaArquivoCsv[29]
                        );
        $sql = 'INSERT INTO estabelecimento
        (cnpj_basico
        ,cnpj_ordem
        ,cnpj_dv
        ,identificador_matriz_filial
        ,nome_fantasia
        ,situacao_cadastral
        ,data_situacao_cadastral
        ,motivo_situacao_cadastral
        ,nome_cidade_exterior
        ,pais
        ,data_inicio_atividade
        ,cnae_fiscal_principal
        ,cnae_fiscal_secundaria
        ,tipo_logradouro
        ,logradouro
        ,numero
        ,complemento
        ,bairro
        ,cep
        ,uf
        ,municipio
        ,ddd_1
        ,telefone_1
        ,ddd_2
        ,telefone_2
        ,ddd_fax
        ,fax
        ,correio_eletronico
        ,situacao_especial
        ,data_situacao_especial)
        VALUES
        (?
        ,?
        ,?
        ,?
        ,?
        ,?
        ,?
        ,?
        ,?
        ,?
        ,?
        ,?
        ,?
        ,?
        ,?
        ,?
        ,?
        ,?
        ,?
        ,?
        ,?
        ,?
        ,?
        ,?
        ,?
        ,?
        ,?
        ,?
        ,?
        ,?)';
        $result = $this->executeSql($sql, $values);
        return true;
    }
}
?>