<?php
/**
 * System generated by SysGen (System Generator with Formdin Framework) 
 * Download SysGenAd: https://github.com/bjverde/sysgenad
 * Download Formdin5 Framework: https://github.com/bjverde/formDin5
 * 
 * SysGen  Version: 0.6.0
 * FormDin Version: 5.0.0
 * 
 * System cnpjrfb created in: 2021-11-19 22:41:06
 */
return [
     "host" => "127.0.0.1"
    ,"port" => "3306"
    ,"name" => "dados_rfb"
    ,"user" => "dados_rfb"
    ,"pass" => "123456"
    ,"type" => "mysql"
    ,"prep" => "1"
    ,"slog" => "SystemSqlLogService"
];