<?php
/**
 * System generated by SysGen (System Generator with Formdin Framework) 
 * Download SysGenAd: https://github.com/bjverde/sysgenad
 * Download Formdin5 Framework: https://github.com/bjverde/formDin5
 * 
 * SysGen  Version: 0.6.0
 * FormDin Version: 5.0.0
 * 
 * System cnpjrfb created in: 2021-11-19 22:41:13
 */
class EstabelecimentoVO
{
    private $cnpj_basico = null;
    private $cnpj_ordem = null;
    private $cnpj_dv = null;
    private $identificador_matriz_filial = null;
    private $nome_fantasia = null;
    private $situacao_cadastral = null;
    private $data_situacao_cadastral = null;
    private $motivo_situacao_cadastral = null;
    private $nome_cidade_exterior = null;
    private $pais = null;
    private $data_inicio_atividade = null;
    private $cnae_fiscal_principal = null;
    private $cnae_fiscal_secundaria = null;
    private $tipo_logradouro = null;
    private $logradouro = null;
    private $numero = null;
    private $complemento = null;
    private $bairro = null;
    private $cep = null;
    private $uf = null;
    private $municipio = null;
    private $ddd_1 = null;
    private $telefone_1 = null;
    private $ddd_2 = null;
    private $telefone_2 = null;
    private $ddd_fax = null;
    private $fax = null;
    private $correio_eletronico = null;
    private $situacao_especial = null;
    private $data_situacao_especial = null;
    public function __construct( $cnpj_basico=null, $cnpj_ordem=null, $cnpj_dv=null, $identificador_matriz_filial=null, $nome_fantasia=null, $situacao_cadastral=null, $data_situacao_cadastral=null, $motivo_situacao_cadastral=null, $nome_cidade_exterior=null, $pais=null, $data_inicio_atividade=null, $cnae_fiscal_principal=null, $cnae_fiscal_secundaria=null, $tipo_logradouro=null, $logradouro=null, $numero=null, $complemento=null, $bairro=null, $cep=null, $uf=null, $municipio=null, $ddd_1=null, $telefone_1=null, $ddd_2=null, $telefone_2=null, $ddd_fax=null, $fax=null, $correio_eletronico=null, $situacao_especial=null, $data_situacao_especial=null ) {
        $this->setCnpj_basico( $cnpj_basico );
        $this->setCnpj_ordem( $cnpj_ordem );
        $this->setCnpj_dv( $cnpj_dv );
        $this->setIdentificador_matriz_filial( $identificador_matriz_filial );
        $this->setNome_fantasia( $nome_fantasia );
        $this->setSituacao_cadastral( $situacao_cadastral );
        $this->setData_situacao_cadastral( $data_situacao_cadastral );
        $this->setMotivo_situacao_cadastral( $motivo_situacao_cadastral );
        $this->setNome_cidade_exterior( $nome_cidade_exterior );
        $this->setPais( $pais );
        $this->setData_inicio_atividade( $data_inicio_atividade );
        $this->setCnae_fiscal_principal( $cnae_fiscal_principal );
        $this->setCnae_fiscal_secundaria( $cnae_fiscal_secundaria );
        $this->setTipo_logradouro( $tipo_logradouro );
        $this->setLogradouro( $logradouro );
        $this->setNumero( $numero );
        $this->setComplemento( $complemento );
        $this->setBairro( $bairro );
        $this->setCep( $cep );
        $this->setUf( $uf );
        $this->setMunicipio( $municipio );
        $this->setDdd_1( $ddd_1 );
        $this->setTelefone_1( $telefone_1 );
        $this->setDdd_2( $ddd_2 );
        $this->setTelefone_2( $telefone_2 );
        $this->setDdd_fax( $ddd_fax );
        $this->setFax( $fax );
        $this->setCorreio_eletronico( $correio_eletronico );
        $this->setSituacao_especial( $situacao_especial );
        $this->setData_situacao_especial( $data_situacao_especial );
    }
    //--------------------------------------------------------------------------------
    public function setCnpj_basico( $strNewValue = null )
    {
        $this->cnpj_basico = preg_replace('/[^0-9]/','',$strNewValue);
    }
    public function getCnpj_basico()
    {
        return $this->cnpj_basico;
    }
    //--------------------------------------------------------------------------------
    public function setCnpj_ordem( $strNewValue = null )
    {
        $this->cnpj_ordem = preg_replace('/[^0-9]/','',$strNewValue);
    }
    public function getCnpj_ordem()
    {
        return $this->cnpj_ordem;
    }
    //--------------------------------------------------------------------------------
    public function setCnpj_dv( $strNewValue = null )
    {
        $this->cnpj_dv = preg_replace('/[^0-9]/','',$strNewValue);
    }
    public function getCnpj_dv()
    {
        return $this->cnpj_dv;
    }
    //--------------------------------------------------------------------------------
    public function setIdentificador_matriz_filial( $strNewValue = null )
    {
        $this->identificador_matriz_filial = $strNewValue;
    }
    public function getIdentificador_matriz_filial()
    {
        return $this->identificador_matriz_filial;
    }
    //--------------------------------------------------------------------------------
    public function setNome_fantasia( $strNewValue = null )
    {
        $this->nome_fantasia = $strNewValue;
    }
    public function getNome_fantasia()
    {
        return $this->nome_fantasia;
    }
    //--------------------------------------------------------------------------------
    public function setSituacao_cadastral( $strNewValue = null )
    {
        $this->situacao_cadastral = $strNewValue;
    }
    public function getSituacao_cadastral()
    {
        return $this->situacao_cadastral;
    }
    //--------------------------------------------------------------------------------
    public function setData_situacao_cadastral( $strNewValue = null )
    {
        $this->data_situacao_cadastral = $strNewValue;
    }
    public function getData_situacao_cadastral()
    {
        return is_null( $this->data_situacao_cadastral ) ? date( 'Y-m-d h:i:s' ) : $this->data_situacao_cadastral;
    }
    //--------------------------------------------------------------------------------
    public function setMotivo_situacao_cadastral( $strNewValue = null )
    {
        $this->motivo_situacao_cadastral = $strNewValue;
    }
    public function getMotivo_situacao_cadastral()
    {
        return $this->motivo_situacao_cadastral;
    }
    //--------------------------------------------------------------------------------
    public function setNome_cidade_exterior( $strNewValue = null )
    {
        $this->nome_cidade_exterior = $strNewValue;
    }
    public function getNome_cidade_exterior()
    {
        return $this->nome_cidade_exterior;
    }
    //--------------------------------------------------------------------------------
    public function setPais( $strNewValue = null )
    {
        $this->pais = $strNewValue;
    }
    public function getPais()
    {
        return $this->pais;
    }
    //--------------------------------------------------------------------------------
    public function setData_inicio_atividade( $strNewValue = null )
    {
        $this->data_inicio_atividade = $strNewValue;
    }
    public function getData_inicio_atividade()
    {
        return is_null( $this->data_inicio_atividade ) ? date( 'Y-m-d h:i:s' ) : $this->data_inicio_atividade;
    }
    //--------------------------------------------------------------------------------
    public function setCnae_fiscal_principal( $strNewValue = null )
    {
        $this->cnae_fiscal_principal = $strNewValue;
    }
    public function getCnae_fiscal_principal()
    {
        return $this->cnae_fiscal_principal;
    }
    //--------------------------------------------------------------------------------
    public function setCnae_fiscal_secundaria( $strNewValue = null )
    {
        $this->cnae_fiscal_secundaria = $strNewValue;
    }
    public function getCnae_fiscal_secundaria()
    {
        return $this->cnae_fiscal_secundaria;
    }
    //--------------------------------------------------------------------------------
    public function setTipo_logradouro( $strNewValue = null )
    {
        $this->tipo_logradouro = $strNewValue;
    }
    public function getTipo_logradouro()
    {
        return $this->tipo_logradouro;
    }
    //--------------------------------------------------------------------------------
    public function setLogradouro( $strNewValue = null )
    {
        $this->logradouro = $strNewValue;
    }
    public function getLogradouro()
    {
        return $this->logradouro;
    }
    //--------------------------------------------------------------------------------
    public function setNumero( $strNewValue = null )
    {
        $this->numero = $strNewValue;
    }
    public function getNumero()
    {
        return $this->numero;
    }
    //--------------------------------------------------------------------------------
    public function setComplemento( $strNewValue = null )
    {
        $this->complemento = $strNewValue;
    }
    public function getComplemento()
    {
        return $this->complemento;
    }
    //--------------------------------------------------------------------------------
    public function setBairro( $strNewValue = null )
    {
        $this->bairro = $strNewValue;
    }
    public function getBairro()
    {
        return $this->bairro;
    }
    //--------------------------------------------------------------------------------
    public function setCep( $strNewValue = null )
    {
        $this->cep = $strNewValue;
    }
    public function getCep()
    {
        return $this->cep;
    }
    //--------------------------------------------------------------------------------
    public function setUf( $strNewValue = null )
    {
        $this->uf = $strNewValue;
    }
    public function getUf()
    {
        return $this->uf;
    }
    //--------------------------------------------------------------------------------
    public function setMunicipio( $strNewValue = null )
    {
        $this->municipio = $strNewValue;
    }
    public function getMunicipio()
    {
        return $this->municipio;
    }
    //--------------------------------------------------------------------------------
    public function setDdd_1( $strNewValue = null )
    {
        $this->ddd_1 = $strNewValue;
    }
    public function getDdd_1()
    {
        return $this->ddd_1;
    }
    //--------------------------------------------------------------------------------
    public function setTelefone_1( $strNewValue = null )
    {
        $this->telefone_1 = $strNewValue;
    }
    public function getTelefone_1()
    {
        return $this->telefone_1;
    }
    //--------------------------------------------------------------------------------
    public function setDdd_2( $strNewValue = null )
    {
        $this->ddd_2 = $strNewValue;
    }
    public function getDdd_2()
    {
        return $this->ddd_2;
    }
    //--------------------------------------------------------------------------------
    public function setTelefone_2( $strNewValue = null )
    {
        $this->telefone_2 = $strNewValue;
    }
    public function getTelefone_2()
    {
        return $this->telefone_2;
    }
    //--------------------------------------------------------------------------------
    public function setDdd_fax( $strNewValue = null )
    {
        $this->ddd_fax = $strNewValue;
    }
    public function getDdd_fax()
    {
        return $this->ddd_fax;
    }
    //--------------------------------------------------------------------------------
    public function setFax( $strNewValue = null )
    {
        $this->fax = $strNewValue;
    }
    public function getFax()
    {
        return $this->fax;
    }
    //--------------------------------------------------------------------------------
    public function setCorreio_eletronico( $strNewValue = null )
    {
        $this->correio_eletronico = $strNewValue;
    }
    public function getCorreio_eletronico()
    {
        return $this->correio_eletronico;
    }
    //--------------------------------------------------------------------------------
    public function setSituacao_especial( $strNewValue = null )
    {
        $this->situacao_especial = $strNewValue;
    }
    public function getSituacao_especial()
    {
        return $this->situacao_especial;
    }
    //--------------------------------------------------------------------------------
    public function setData_situacao_especial( $strNewValue = null )
    {
        $this->data_situacao_especial = $strNewValue;
    }
    public function getData_situacao_especial()
    {
        return is_null( $this->data_situacao_especial ) ? date( 'Y-m-d h:i:s' ) : $this->data_situacao_especial;
    }
    //--------------------------------------------------------------------------------
}
?>