<?php
/**
 * System generated by SysGen (System Generator with Formdin Framework) 
 * Download SysGenAd: https://github.com/bjverde/sysgenad
 * Download Formdin5 Framework: https://github.com/bjverde/formDin5
 * 
 * SysGen  Version: 0.6.0
 * FormDin Version: 5.0.0
 * 
 * System cnpjrfb created in: 2021-11-19 22:41:13
 */
class MotiVO
{
    private $codigo = null;
    private $descricao = null;
    public function __construct( $codigo=null, $descricao=null ) {
        $this->setCodigo( $codigo );
        $this->setDescricao( $descricao );
    }
    //--------------------------------------------------------------------------------
    public function setCodigo( $strNewValue = null )
    {
        $this->codigo = $strNewValue;
    }
    public function getCodigo()
    {
        return $this->codigo;
    }
    //--------------------------------------------------------------------------------
    public function setDescricao( $strNewValue = null )
    {
        $this->descricao = $strNewValue;
    }
    public function getDescricao()
    {
        return $this->descricao;
    }
    //--------------------------------------------------------------------------------
}
?>