<?php
/**
 * System generated by SysGen (System Generator with Formdin Framework) 
 * Download SysGenAd: https://github.com/bjverde/sysgenad
 * Download Formdin5 Framework: https://github.com/bjverde/formDin5
 * 
 * SysGen  Version: 0.6.0
 * FormDin Version: 5.0.0
 * 
 * System cnpjrfb created in: 2021-11-19 22:41:14
 */
class SimplesVO
{
    private $cnpj_basico = null;
    private $opcao_pelo_simples = null;
    private $data_opcao_simples = null;
    private $data_exclusao_simples = null;
    private $opcao_mei = null;
    private $data_opcao_mei = null;
    private $data_exclusao_mei = null;
    public function __construct( $cnpj_basico=null, $opcao_pelo_simples=null, $data_opcao_simples=null, $data_exclusao_simples=null, $opcao_mei=null, $data_opcao_mei=null, $data_exclusao_mei=null ) {
        $this->setCnpj_basico( $cnpj_basico );
        $this->setOpcao_pelo_simples( $opcao_pelo_simples );
        $this->setData_opcao_simples( $data_opcao_simples );
        $this->setData_exclusao_simples( $data_exclusao_simples );
        $this->setOpcao_mei( $opcao_mei );
        $this->setData_opcao_mei( $data_opcao_mei );
        $this->setData_exclusao_mei( $data_exclusao_mei );
    }
    //--------------------------------------------------------------------------------
    public function setCnpj_basico( $strNewValue = null )
    {
        $this->cnpj_basico = preg_replace('/[^0-9]/','',$strNewValue);
    }
    public function getCnpj_basico()
    {
        return $this->cnpj_basico;
    }
    //--------------------------------------------------------------------------------
    public function setOpcao_pelo_simples( $strNewValue = null )
    {
        $this->opcao_pelo_simples = $strNewValue;
    }
    public function getOpcao_pelo_simples()
    {
        return $this->opcao_pelo_simples;
    }
    //--------------------------------------------------------------------------------
    public function setData_opcao_simples( $strNewValue = null )
    {
        $this->data_opcao_simples = $strNewValue;
    }
    public function getData_opcao_simples()
    {
        return is_null( $this->data_opcao_simples ) ? date( 'Y-m-d h:i:s' ) : $this->data_opcao_simples;
    }
    //--------------------------------------------------------------------------------
    public function setData_exclusao_simples( $strNewValue = null )
    {
        $this->data_exclusao_simples = $strNewValue;
    }
    public function getData_exclusao_simples()
    {
        return is_null( $this->data_exclusao_simples ) ? date( 'Y-m-d h:i:s' ) : $this->data_exclusao_simples;
    }
    //--------------------------------------------------------------------------------
    public function setOpcao_mei( $strNewValue = null )
    {
        $this->opcao_mei = $strNewValue;
    }
    public function getOpcao_mei()
    {
        return $this->opcao_mei;
    }
    //--------------------------------------------------------------------------------
    public function setData_opcao_mei( $strNewValue = null )
    {
        $this->data_opcao_mei = $strNewValue;
    }
    public function getData_opcao_mei()
    {
        return is_null( $this->data_opcao_mei ) ? date( 'Y-m-d h:i:s' ) : $this->data_opcao_mei;
    }
    //--------------------------------------------------------------------------------
    public function setData_exclusao_mei( $strNewValue = null )
    {
        $this->data_exclusao_mei = $strNewValue;
    }
    public function getData_exclusao_mei()
    {
        return is_null( $this->data_exclusao_mei ) ? date( 'Y-m-d h:i:s' ) : $this->data_exclusao_mei;
    }
    //--------------------------------------------------------------------------------
}
?>