<?php
/**
 * System generated by SysGen (System Generator with Formdin Framework) 
 * Download SysGenAd: https://github.com/bjverde/sysgenad
 * Download Formdin5 Framework: https://github.com/bjverde/formDin5
 * 
 * SysGen  Version: 0.6.0
 * FormDin Version: 5.0.0
 * 
 * System cnpjrfb created in: 2021-11-19 22:41:14
 */
class SociosVO
{
    private $cnpj_basico = null;
    private $identificador_socio = null;
    private $nome_socio_razao_social = null;
    private $cpf_cnpj_socio = null;
    private $qualificacao_socio = null;
    private $data_entrada_sociedade = null;
    private $pais = null;
    private $representante_legal = null;
    private $nome_do_representante = null;
    private $qualificacao_representante_legal = null;
    private $faixa_etaria = null;
    public function __construct( $cnpj_basico=null, $identificador_socio=null, $nome_socio_razao_social=null, $cpf_cnpj_socio=null, $qualificacao_socio=null, $data_entrada_sociedade=null, $pais=null, $representante_legal=null, $nome_do_representante=null, $qualificacao_representante_legal=null, $faixa_etaria=null ) {
        $this->setCnpj_basico( $cnpj_basico );
        $this->setIdentificador_socio( $identificador_socio );
        $this->setNome_socio_razao_social( $nome_socio_razao_social );
        $this->setCpf_cnpj_socio( $cpf_cnpj_socio );
        $this->setQualificacao_socio( $qualificacao_socio );
        $this->setData_entrada_sociedade( $data_entrada_sociedade );
        $this->setPais( $pais );
        $this->setRepresentante_legal( $representante_legal );
        $this->setNome_do_representante( $nome_do_representante );
        $this->setQualificacao_representante_legal( $qualificacao_representante_legal );
        $this->setFaixa_etaria( $faixa_etaria );
    }
    //--------------------------------------------------------------------------------
    public function setCnpj_basico( $strNewValue = null )
    {
        $this->cnpj_basico = preg_replace('/[^0-9]/','',$strNewValue);
    }
    public function getCnpj_basico()
    {
        return $this->cnpj_basico;
    }
    //--------------------------------------------------------------------------------
    public function setIdentificador_socio( $strNewValue = null )
    {
        $this->identificador_socio = $strNewValue;
    }
    public function getIdentificador_socio()
    {
        return $this->identificador_socio;
    }
    //--------------------------------------------------------------------------------
    public function setNome_socio_razao_social( $strNewValue = null )
    {
        $this->nome_socio_razao_social = $strNewValue;
    }
    public function getNome_socio_razao_social()
    {
        return $this->nome_socio_razao_social;
    }
    //--------------------------------------------------------------------------------
    public function setCpf_cnpj_socio( $strNewValue = null )
    {
        $this->cpf_cnpj_socio = preg_replace('/[^0-9]/','',$strNewValue);
    }
    public function getCpf_cnpj_socio()
    {
        return $this->cpf_cnpj_socio;
    }
    //--------------------------------------------------------------------------------
    public function setQualificacao_socio( $strNewValue = null )
    {
        $this->qualificacao_socio = $strNewValue;
    }
    public function getQualificacao_socio()
    {
        return $this->qualificacao_socio;
    }
    //--------------------------------------------------------------------------------
    public function setData_entrada_sociedade( $strNewValue = null )
    {
        $this->data_entrada_sociedade = $strNewValue;
    }
    public function getData_entrada_sociedade()
    {
        return is_null( $this->data_entrada_sociedade ) ? date( 'Y-m-d h:i:s' ) : $this->data_entrada_sociedade;
    }
    //--------------------------------------------------------------------------------
    public function setPais( $strNewValue = null )
    {
        $this->pais = $strNewValue;
    }
    public function getPais()
    {
        return $this->pais;
    }
    //--------------------------------------------------------------------------------
    public function setRepresentante_legal( $strNewValue = null )
    {
        $this->representante_legal = $strNewValue;
    }
    public function getRepresentante_legal()
    {
        return $this->representante_legal;
    }
    //--------------------------------------------------------------------------------
    public function setNome_do_representante( $strNewValue = null )
    {
        $this->nome_do_representante = $strNewValue;
    }
    public function getNome_do_representante()
    {
        return $this->nome_do_representante;
    }
    //--------------------------------------------------------------------------------
    public function setQualificacao_representante_legal( $strNewValue = null )
    {
        $this->qualificacao_representante_legal = $strNewValue;
    }
    public function getQualificacao_representante_legal()
    {
        return $this->qualificacao_representante_legal;
    }
    //--------------------------------------------------------------------------------
    public function setFaixa_etaria( $strNewValue = null )
    {
        $this->faixa_etaria = $strNewValue;
    }
    public function getFaixa_etaria()
    {
        return $this->faixa_etaria;
    }
    //--------------------------------------------------------------------------------
}
?>