<?php
/**
 * System generated by SysGen (System Generator with Formdin Framework) 
 * Download SysGenAd: https://github.com/bjverde/sysgenad
 * Download Formdin5 Framework: https://github.com/bjverde/formDin5
 * 
 * SysGen  Version: 0.6.0
 * FormDin Version: 5.0.0
 * 
 * System cnpjrfb2 created in: 2021-11-20 00:51:44
 */

class sociosForm extends TPage
{

    protected $form; //Registration form Adianti
    protected $frm;  //Registration component FormDin 5
    protected $datagrid; //Listing
    protected $pageNavigation;

    // trait com onReload, onSearch, onDelete, onClear, onEdit, show
    use Adianti\Base\AdiantiStandardFormTrait;
    // trait com onReload, onSearch, onDelete...
    use Adianti\Base\AdiantiStandardListTrait;

    public function __construct()
    {
        parent::__construct();
        // $this->adianti_target_container = 'adianti_right_panel';

        $this->setDatabase('maindatabase'); // define the database
        $this->setActiveRecord('socios'); // define the Active Record
        $this->setDefaultOrder('CNPJ_BASICO', 'asc'); // define the default order

        $primaryKey = 'CNPJ_BASICO';
        $this->frm = new TFormDin($this,'socios');
        $frm = $this->frm;
        $frm->enableCSRFProtection(); // Protection cross-site request forgery 
        $frm->addTextField('CNPJ_BASICO', 'Cnpj Basico',8,true,8);
        $frm->addNumberField('IDENTIFICADOR_SOCIO', 'Id Entificador Socio',10,true,0);
        $frm->addMemoField('NOME_SOCIO_RAZAO_SOCIAL', 'Nome Socio Razao Social',1000,false,80,3);
        $frm->addTextField('CPF_CNPJ_SOCIO', 'Cpf Cnpj Socio',45,false,45);
        //$frm->getLabel('CPF_CNPJ_SOCIO')->setToolTip('CPF OU CNPJ DO SÓCIO (SÓCIO ESTRANGEIRO NÃO TEM ESTA INFORMAÇÃO).');
        $controllerQuals = new QualsController();
        $listQuals = $controllerQuals->selectAll();
        $frm->addSelectField('QUALIFICACAO_SOCIO', 'Qualificação Socio',false,$listQuals,null,null,null,null,null,null,' ',null);
        //$frm->getLabel('QUALIFICACAO_SOCIO')->setToolTip('CÓDIGO DA QUALIFICAÇÃO DO SÓCIO');
        $frm->addDateTimeField('DATA_ENTRADA_SOCIEDADE', 'Data Entrada Sociedade',false,null,null,null,null,'dd/mm/yyyy hh:ii',null,null,null,null,'yyyy-mm-dd hh:ii');
        $controllerPais = new PaisController();
        $listPais = $controllerPais->selectAll();
        $frm->addSelectField('PAIS', 'Pais',false,$listPais,null,null,null,null,null,null,' ',null);
        //$frm->getLabel('PAIS')->setToolTip('CÓDIGO PAÍS DO SÓCIO ESTRANGEIRO');
        $frm->addTextField('REPRESENTANTE_LEGAL', 'Representante Legal',45,false,45);
        //$frm->getLabel('REPRESENTANTE_LEGAL')->setToolTip('NÚMERO DO CPF DO REPRESENTANTE LEGAL');
        $frm->addMemoField('NOME_DO_REPRESENTANTE', 'Nome Do Representante',500,false,80,3);
        $controllerQuals = new QualsController();
        $listQuals = $controllerQuals->selectAll();
        $frm->addSelectField('QUALIFICACAO_REPRESENTANTE_LEGAL', 'Qualificação Representante Legal',false,$listQuals,null,null,null,null,null,null,' ',null);
        //$frm->getLabel('QUALIFICACAO_REPRESENTANTE_LEGAL')->setToolTip('CÓDIGO DA QUALIFICAÇÃO DO REPRESENTANTE LEGAL');
        $frm->addNumberField('FAIXA_ETARIA', 'Faixa Etaria',10,false,0);

        // O Adianti permite a Internacionalização - A função _t('string') serve
        //para traduzir termos no sistema. Veja ApplicationTranslator escrevendo
        //primeiro em ingles e depois traduzindo
        $frm->setAction( _t('Save'), 'onSave', null, 'fa:save', 'green' );
        $frm->setActionLink( _t('Clear'), 'onClear', null, 'fa:eraser', 'red');

        $this->form = $frm->show();
        $this->form->setData( TSession::getValue(__CLASS__.'_filter_data'));

        $mixUpdateFields = $primaryKey.'|'.$primaryKey
                        .',IDENTIFICADOR_SOCIO|IDENTIFICADOR_SOCIO'
                        .',NOME_SOCIO_RAZAO_SOCIAL|NOME_SOCIO_RAZAO_SOCIAL'
                        .',CPF_CNPJ_SOCIO|CPF_CNPJ_SOCIO'
                        .',QUALIFICACAO_SOCIO|QUALIFICACAO_SOCIO'
                        .',DATA_ENTRADA_SOCIEDADE|DATA_ENTRADA_SOCIEDADE'
                        .',PAIS|PAIS'
                        .',REPRESENTANTE_LEGAL|REPRESENTANTE_LEGAL'
                        .',NOME_DO_REPRESENTANTE|NOME_DO_REPRESENTANTE'
                        .',QUALIFICACAO_REPRESENTANTE_LEGAL|QUALIFICACAO_REPRESENTANTE_LEGAL'
                        .',FAIXA_ETARIA|FAIXA_ETARIA'
                        ;
        $grid = new TFormDinGrid($this,'gd','Data Grid');
        $grid->setUpdateFields($mixUpdateFields);
        $grid->addColumn($primaryKey,'id');
        $grid->addColumn('IDENTIFICADOR_SOCIO','Id Entificador Socio');
        $grid->addColumn('NOME_SOCIO_RAZAO_SOCIAL','Nome Socio Razao Social');
        $grid->addColumn('CPF_CNPJ_SOCIO','Cpf Cnpj Socio');
        $grid->addColumn('QUALIFICACAO_SOCIO','Qualificação Socio');
        $grid->addColumnFormatDate('DATA_ENTRADA_SOCIEDADE','Data Entrada Sociedade',null,'left','dd/mm/yyyy hh:ii');
        $grid->addColumn('PAIS','Pais');
        $grid->addColumn('REPRESENTANTE_LEGAL','Representante Legal');
        $grid->addColumn('NOME_DO_REPRESENTANTE','Nome Do Representante');
        $grid->addColumn('QUALIFICACAO_REPRESENTANTE_LEGAL','Qualificação Representante Legal');
        $grid->addColumn('FAIXA_ETARIA','Faixa Etaria');

        $this->datagrid = $grid->show();
        $this->pageNavigation = $grid->getPageNavigation();
        $panelGroupGrid = $grid->getPanelGroupGrid();


        // creates the page structure using a table
        $formDinBreadCrumb = new TFormDinBreadCrumb(__CLASS__);
        $vbox = $formDinBreadCrumb->getAdiantiObj();
        $vbox->add($this->form);
        $vbox->add($panelGroupGrid);

        // add the table inside the page
        parent::add($vbox);
    }

    //--------------------------------------------------------------------------------
    /**
     * Close right panel
     */
     /*
    public function onClose()
    {
        TScript::create("Template.closeRightPanel()");
    } //END onClose
     */

    //--------------------------------------------------------------------------------
    public function onSave($param)
    {
        $data = $this->form->getData();
        //Função do FormDin para Debug
        FormDinHelper::d($param,'$param');
        FormDinHelper::debug($data,'$data');
        FormDinHelper::debug($_REQUEST,'$_REQUEST');

        try{
            $this->form->validate();
            $this->form->setData($data);
            $vo = new SociosVO();
            $this->frm->setVo( $vo ,$data ,$param );
            $controller = new SociosController();
            $resultado = $controller->save( $vo );
            if( is_int($resultado) && $resultado!=0 ) {
                //$text = TFormDinMessage::messageTransform($text); //Tranform Array in Msg Adianti
                $this->onReload();
                $this->frm->addMessage( _t('Record saved') );
                //$this->frm->clearFields();
            }else{
                $this->frm->addMessage($resultado);
            }
        }catch (Exception $e){
            new TMessage(TFormDinMessage::TYPE_ERROR, $e->getMessage());
        } //END TryCatch
    } //END onSave

}