<?php
/**
 * System generated by SysGen (System Generator with Formdin Framework) 
 * Download SysGen: https://github.com/bjverde/sysgen
 * Download Formdin Framework: https://github.com/bjverde/formDin
 * 
 * SysGen  Version: 1.11.0
 * FormDin Version: 4.11.0
 * 
 * System concursomembroadm created in: 2021-03-10 20:42:27
 */
class CnaeDAO  extends Dao
{
    private static $sqlBasicSelect = "select
                                      codigo
                                     ,descricao
                                     from cnae ";

    public function __construct($tpdo=null)
    {
        parent::__construct($tpdo);
        $this->setTabelaName('cnae');
    }
    //--------------------------------------------------------------------------------
    public function insert( ConcursoVO $objVo )
    {
        $values = array(  $objVo->getSnome() 
                        , $objVo->getMvalorinscricao() 
                        , $objVo->getDtinicioinscricao() 
                        , $objVo->getDtfiminscricao() 
                        , $objVo->getIminimoquestaocorretaprovaobjetiva() 
                        , $objVo->getDtiniciogru() 
                        , $objVo->getDtfimgru() 
                        , $objVo->getDtiniciocomprovante() 
                        , $objVo->getDtfimcomprovante() 
                        );
        $sql = 'insert into dbo.concurso(
                                 snome
                                ,mvalorinscricao
                                ,dtinicioinscricao
                                ,dtfiminscricao
                                ,iminimoquestaocorretaprovaobjetiva
                                ,dtiniciogru
                                ,dtfimgru
                                ,dtiniciocomprovante
                                ,dtfimcomprovante
                                ) values (?,?,?,?,?,?,?,?,?)';
        $result = $this->tpdo->executeSql($sql, $values);
        $result = $this->tpdo->getLastInsertId();
        return intval($result);
    }
}
?>